/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.auritylab.graphql.kotlin.toolkit

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
